---
title: Sounds
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Listening to the sounds
baseurl: 
url: https://raulhammerl.github.io/sounds
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
staticman_url: https://sounds-staticman.herokuapp.com/v2/entry/raulhammerl/sounds/master/comments
future: false
paginate: 8
paginate_path: "/page:num/"
name: Sounds
