## Jekyll Settings 

title: Sounds
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Listening to the sounds
baseurl: "/sounds"# the subpath of your site, e.g. /blog
url: "https://raulhammerl.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate


# Staticman Comments
staticman_url: https://sounds-staticman.herokuapp.com/v2/entry/raulhammerl/sounds/master/comments

future: false

# Pagination
paginate: 8
paginate_path: "/page:num/"

# RSS Feed
name: Sounds
url: raulhammerl.github.io/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/de
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
